"""Shared contracts for MacroMind's modular data pipeline."""

from pipeline.contracts import (
    DataFrequency,
    Observation,
    PipelineRunContext,
    RunMode,
    SourceBatch,
    SourceError,
    SourceStatus,
)
from pipeline.adapters import LiveAdapter
from pipeline.coverage import (
    CoverageReport,
    MetricCoverage,
    PipelineCoverageReport,
    build_coverage_report,
    combine_coverage_reports,
)
from pipeline.fallback import (
    FallbackAction,
    FallbackDecision,
    FallbackPolicy,
    FallbackResolution,
    FallbackScope,
    LIVE_FALLBACK_POLICIES,
    decide_fallback,
    policy_for_source,
    resolve_with_policy,
)
from pipeline.store import (
    DEFAULT_OBSERVATION_DB,
    ImmutableStoreConflict,
    ObservationStore,
    StoredObservation,
    StoreWriteResult,
)
from pipeline.quality import (
    DataQualityReport,
    DateSemantics,
    FreshnessBasis,
    GateAction,
    MetricQualityRule,
    QUALITY_POLICY_VERSION,
    QUALITY_RULES,
    QualityGate,
    QualityGateResult,
    QualityIssue,
    QualityStatus,
    run_quality_gates,
)

__all__ = [
    "DataFrequency",
    "DataQualityReport",
    "DEFAULT_OBSERVATION_DB",
    "CoverageReport",
    "FallbackAction",
    "FallbackDecision",
    "FallbackPolicy",
    "FallbackResolution",
    "FallbackScope",
    "FreshnessBasis",
    "GateAction",
    "LIVE_FALLBACK_POLICIES",
    "ImmutableStoreConflict",
    "LiveAdapter",
    "MetricCoverage",
    "MetricQualityRule",
    "Observation",
    "ObservationStore",
    "PipelineCoverageReport",
    "PipelineRunContext",
    "QUALITY_POLICY_VERSION",
    "QUALITY_RULES",
    "QualityGate",
    "QualityGateResult",
    "QualityIssue",
    "QualityStatus",
    "DateSemantics",
    "RunMode",
    "SourceBatch",
    "SourceError",
    "SourceStatus",
    "StoredObservation",
    "StoreWriteResult",
    "build_coverage_report",
    "combine_coverage_reports",
    "decide_fallback",
    "policy_for_source",
    "resolve_with_policy",
    "run_quality_gates",
]
